import type { ReactNode } from "react";

export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "callout"; variant: "warning" | "note" | "danger"; title?: string; text: string }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "flow"; steps: string[] }
  | { type: "quote"; text: string }
  | { type: "link"; label: string; href: string };

export const docsContent: Record<string, Block[]> = {
  "what-is-utopia": [
    { type: "quote", text: "Your Web3 wallet. Your Visa-linked account. One app." },
    { type: "p", text: "U-Topia combines Web3 wallet ownership with real-world financial access, letting eligible users hold digital assets, spend fiat and crypto, and tap into modern financial tools through a single app experience. Regulated banking and issuing partners handle the rails. You keep control of the wallet." },
    { type: "h3", text: "What U-Topia gives you" },
    { type: "ul", items: [
      "A non-custodial Web3 wallet — you control your credentials, you control your assets.",
      "Visa-linked account access — through regulated banking and issuing partners connected to the Visa network.",
      "Fiat-and-crypto usability — for everyday spending, where supported.",
      "One unified experience — wallet, accounts, security, and transactions in one place.",
    ]},
    { type: "callout", variant: "note", text: "Availability of U-Topia features, account access, Visa-linked credentials, fiat and crypto services, and supported jurisdictions depends on partner availability, compliance requirements, local regulations, user eligibility, and final product launch decisions." },
  ],
  "why-utopia-exists": [
    { type: "quote", text: "Most people don't get to choose between Web3 and modern banking. They get stuck with one or the other." },
    { type: "p", text: "Across the world, eligible users hit the same walls:" },
    { type: "ul", items: [
      "Banking access is hard — especially across borders, or for people with mobility, identity, or jurisdictional friction.",
      "Crypto wallets feel disconnected — digital assets sit idle, with no bridge to everyday spending or accounts.",
      "Card networks need regulated infrastructure — which most Web3 apps can't provide on their own.",
      "Compliance, security, and usability rarely come in one app — users end up juggling tools, custodians, and exchanges.",
    ]},
    { type: "p", text: "U-Topia exists to close that gap. By combining a non-custodial wallet with Visa-linked account access through regulated banking and issuing partners, eligible users get one app for both worlds — Web3 ownership and real-world financial utility." },
  ],
  "vision": [
    { type: "p", text: "Make global financial access work for the next billion users by combining Web3 ownership with real-world rails." },
    { type: "p", text: "U-Topia is building toward a world where eligible users don't have to choose between owning their wallet and using everyday financial tools. The vision rests on four ideas:" },
    { type: "ul", items: [
      "One app, both worlds — wallet, fiat, crypto, and payment activity in a single experience, where supported.",
      "Users own their wallet — Web3 non-custodial design keeps credentials in the user's hands.",
      "Regulated partners power the rails — banking, issuing, payments, settlement, and compliance handled by licensed institutions.",
      "Real-world utility — practical financial tools for eligible users in supported jurisdictions, not just speculation.",
    ]},
    { type: "callout", variant: "warning", title: "Not a Bank Disclaimer", text: "U-Topia is not a bank and should not be described as one unless it has received the required licenses. Banking, issuing, payment, settlement, and compliance services may be provided by regulated partners." },
  ],
  "core-pillars": [
    { type: "p", text: "U-Topia is built around seven core pillars. Each one is essential. Remove any pillar and the rest can't stand on their own." },
    { type: "ol", items: [
      "Web3 non-custodial wallet — user-controlled wallet experience for supported digital assets.",
      "Visa-linked account access — eligible users may receive Visa-linked account or payment credentials through approved partners.",
      "Banking and issuing partner infrastructure — regulated partners provide accounts, issuing, compliance, and settlement.",
      "Fiat and crypto functionality — where approved, the app supports fiat and crypto activity in one experience.",
      "Global eligibility and access — designed to support eligible users globally, subject to jurisdictional availability.",
      "Compliance and security layer — KYC, AML, sanctions screening, and risk controls.",
      "App-based user experience — a unified mobile-first experience for wallet, account, and security activity.",
    ]},
  ],
  "product-summary": [
    { type: "table", headers: ["Product Layer", "What It Means", "Why It Matters"], rows: [
      ["Web3 wallet", "User-controlled wallet experience", "Gives users Web3-native access"],
      ["Visa-linked account access", "Account/payment capabilities through partners", "Connects digital finance to real-world payment rails"],
      ["Banking partners", "Regulated institutions provide accounts, compliance, and settlement", "Enables compliant financial access"],
      ["Issuing partners", "Approved partners issue card and account credentials", "Enables payment-network connectivity"],
      ["Fiat and crypto", "Traditional and digital asset support, where approved", "Makes the app more useful for everyday finance"],
      ["Compliance", "KYC, AML, sanctions, eligibility controls", "Required for regulated financial access"],
      ["Security", "Wallet protection, recovery, authentication", "Protects user access and account activity"],
    ]},
    { type: "callout", variant: "warning", title: "No Guarantee Disclaimer", text: "U-Topia does not guarantee account approval, card issuance, partner acceptance, transaction approval, asset value, or uninterrupted service." },
  ],
  "user-flow": [
    { type: "p", text: "Here's how a typical user gets onboarded and active in U-Topia:" },
    { type: "ol", items: [
      "User downloads the U-Topia app.",
      "User creates or connects a Web3 wallet.",
      "User completes required identity and compliance checks (KYC, screening, eligibility review).",
      "Banking or issuing partners review eligibility against their internal requirements.",
      "Eligible users may receive Visa-linked account or payment credential access.",
      "Users can manage supported fiat and crypto features inside the app.",
      "Transactions and conversions are processed through approved infrastructure partners.",
    ]},
    { type: "callout", variant: "note", title: "Compliance Disclaimer", text: "KYC, AML, sanctions screening, jurisdictional restrictions, tax reporting, and partner-bank requirements may apply." },
  ],
  "user-journey": [
    { type: "flow", steps: [
      "Download U-Topia App",
      "Create or Connect Web3 Wallet",
      "Complete Required Identity and Compliance Checks (KYC)",
      "Banking / Issuing Partner Review",
      "Eligible User Receives Visa-Linked Account Access",
      "Use Supported Fiat, Crypto, and Payment Features",
      "Manage Wallet, Account, Security, and Activity",
    ]},
  ],
  "non-custodial-meaning": [
    { type: "p", text: "A non-custodial wallet means the user controls access to the wallet, not a centralized custodian." },
    { type: "p", text: "In practice, \"non-custodial\" covers a range of wallet designs, each with different control and recovery models: traditional private-key wallets, smart wallets, account-abstraction wallets, MPC-based wallets, social-recovery wallets, and passkey-based wallets." },
    { type: "p", text: "What stays consistent across all of them: the user's credentials, not a custodian's, unlock the wallet." },
  ],
  "user-control": [
    { type: "p", text: "In a non-custodial wallet, the user is in control — and that comes with responsibility:" },
    { type: "ul", items: [
      "Users control their wallet credentials. No custodian holds them.",
      "Users are responsible for safeguarding access — recovery phrases, keys, passkeys, or whatever recovery mechanism the final design uses.",
      "Security and recovery are explained at onboarding. Users see clearly what they need to protect and how to recover access.",
      "Losing credentials may mean losing access. The recovery model determines whether and how access can be restored.",
    ]},
    { type: "callout", variant: "warning", title: "Non-Custodial Wallet Disclaimer", text: "Non-custodial wallet features require users to protect wallet credentials. Loss of credentials may result in loss of access, depending on the final wallet recovery design." },
  ],
  "wallet-architecture": [
    { type: "p", text: "Web3 wallets come in several architectural flavors, each with different trade-offs between user control, recovery, and usability. The most common patterns:" },
    { type: "ul", items: [
      "Traditional private-key wallet — user holds keys directly. Maximum control, maximum responsibility.",
      "Smart wallet — programmable wallet contracts supporting gas abstraction, batched transactions, and custom permissions.",
      "Account abstraction — flexible authorization patterns including session keys and policy-based controls.",
      "MPC (multi-party computation) — key material distributed across parties for resilience, removing the single-point-of-failure problem.",
      "Social recovery — trusted guardians help users restore access without a single seed phrase.",
      "Passkey-based access — device-bound credentials that replace or supplement seed phrases.",
    ]},
    { type: "callout", variant: "note", text: "U-Topia's final wallet architecture will be confirmed ahead of launch, with clear documentation of the control and recovery model users can expect." },
  ],
  "wallet-security-diagram": [
    { type: "flow", steps: [
      "User",
      "Authentication",
      "Web3 Wallet",
      "Recovery System / Supported Digital Assets / U-Topia App Interface",
      "Risk and Security Monitoring",
    ]},
  ],
  "visa-linked-meaning": [
    { type: "p", text: "Visa-linked access means eligible users may receive account or payment credentials that connect to the Visa network through approved banking, issuing, processing, and program-management partners." },
    { type: "p", text: "Importantly, U-Topia is not Visa, and U-Topia is not a bank. Connectivity to the Visa network depends on regulated partners that hold the necessary licenses, agreements, and operational responsibilities." },
  ],
  "utopia-role": [
    { type: "p", text: "U-Topia's role focuses on the user-facing experience and product coordination:" },
    { type: "ul", items: [
      "U-Topia provides the app experience.",
      "U-Topia provides the wallet interface.",
      "U-Topia coordinates user experience and product flow.",
      "Regulated partners may provide accounts, issuing, settlement, card-network connectivity, and compliance services.",
    ]},
    { type: "callout", variant: "warning", text: "U-Topia should not be described as directly issuing Visa cards or as holding a direct Visa license unless this has been formally confirmed." },
  ],
  "partner-model": [
    { type: "table", headers: ["Layer", "Possible Responsible Party"], rows: [
      ["App experience", "U-Topia"],
      ["Wallet interface", "U-Topia / wallet infrastructure"],
      ["KYC / compliance checks", "Compliance provider / banking partner"],
      ["Account services", "Banking partner"],
      ["Card/account issuing", "Issuing partner"],
      ["Payment network", "Visa network"],
      ["Processing", "Processor / program manager"],
      ["Settlement", "Bank / issuer / processor"],
      ["Crypto infrastructure", "Wallet/blockchain/stablecoin providers, if approved"],
    ]},
  ],
  "account-flow": [
    { type: "flow", steps: [
      "U-Topia App",
      "KYC / Compliance",
      "Banking Partner",
      "Issuing Partner",
      "Visa-Linked Account or Credential",
      "Visa Network",
      "Merchants / Payment Acceptance",
    ]},
  ],
  "banking-partners": [
    { type: "ul", items: [
      "Regulated financial services require licensed partners with banking authority in the relevant jurisdiction.",
      "Banking partners may support accounts, compliance, settlement, and customer eligibility decisions.",
      "Partner banks help fintech apps provide financial services without the app itself becoming a bank in every jurisdiction.",
      "Banking partners typically own the regulatory relationships with supervisors and enforce program-level controls.",
    ]},
  ],
  "issuing-partners": [
    { type: "ul", items: [
      "Issuing partners support card/account credentials that are recognized by payment networks.",
      "Issuers may connect accounts to payment networks like Visa.",
      "Issuing partners may manage card rules, transaction approvals, chargeback handling, and regulatory obligations.",
      "Issuer policies typically define eligibility, transaction limits, jurisdictional restrictions, and acceptable use.",
    ]},
  ],
  "partner-policy": [
    { type: "callout", variant: "warning", text: "Insert confirmed banking and issuing partners only after legal and partner approval." },
    { type: "p", text: "Specific partner names should not appear in public materials until partnership agreements and legal review are complete. Premature naming can create compliance, branding, and contractual issues." },
    { type: "ul", items: [
      "Confirm final banking partners",
      "Confirm final issuing partners",
      "Confirm final processor or program manager",
      "Confirm final Visa relationship structure",
    ]},
  ],
  "fiat-features": [
    { type: "p", text: "Subject to final approval, possible fiat functionality may include:" },
    { type: "ul", items: [
      "Fiat balances",
      "Account access",
      "Virtual or physical card credentials",
      "Spending",
      "Transfers",
      "Account dashboard",
      "Transaction history",
    ]},
    { type: "callout", variant: "note", text: "[Confirm supported fiat currencies] [Confirm card type — debit, prepaid, virtual, physical, or other]" },
  ],
  "crypto-features": [
    { type: "p", text: "Subject to final approval, possible crypto functionality may include:" },
    { type: "ul", items: [
      "Crypto wallet access",
      "Stablecoin support, if approved",
      "Supported tokens, if approved",
      "Crypto-to-fiat conversion, if approved",
      "Blockchain transaction history",
      "Wallet activity",
    ]},
  ],
  "fiat-crypto-bridge": [
    { type: "p", text: "U-Topia is designed to reduce the gap between digital-asset ownership and everyday financial utility by connecting Web3 wallet access with partner-powered fiat and payment infrastructure." },
    { type: "p", text: "Placeholders for items pending confirmation:" },
    { type: "ul", items: [
      "[Confirm supported assets]",
      "[Confirm stablecoin support]",
      "[Confirm conversion partners]",
      "[Confirm fees]",
      "[Confirm settlement model]",
    ]},
    { type: "callout", variant: "danger", title: "Crypto Risk Disclaimer", text: "Digital assets may be volatile and may not be protected by the same insurance or regulatory protections as traditional bank deposits. Users should understand the risks before using crypto-related features." },
  ],
  "global-direction": [
    { type: "p", text: "U-Topia aims to make Visa-linked financial access easier for eligible users globally through an app-based Web3 wallet experience powered by regulated partners." },
    { type: "p", text: "The goal is broad reach for eligible users, achieved through partner expansion, jurisdictional review, and compliance scaling — not through bypassing local regulation." },
  ],
  "eligibility": [
    { type: "p", text: "Access may depend on:" },
    { type: "ul", items: [
      "Country of residence", "Age", "Identity verification", "Partner-bank requirements", "Sanctions screening", "Local law", "Card program rules", "Supported currencies", "Risk review",
    ]},
    { type: "callout", variant: "note", text: "[Confirm supported jurisdictions] [Confirm age requirements] [Confirm compliance providers]" },
  ],
  "financial-inclusion": [
    { type: "ul", items: [
      "Many users globally may lack access to modern financial services such as checking accounts, payment cards, and cross-border transfers.",
      "Mobile-first finance can expand access in regions where traditional branch banking is limited.",
      "Web3 wallets can give users digital ownership tools and a portable identity-and-asset layer.",
      "Partner-powered financial infrastructure can connect digital access to real-world payment systems where licensed institutions enable it.",
    ]},
    { type: "h3", text: "References" },
    { type: "ul", items: [
      "World Bank. Global Findex Database — https://www.worldbank.org/en/publication/globalfindex",
      "World Bank. Remittance Prices Worldwide — https://remittanceprices.worldbank.org/",
      "Bank for International Settlements (BIS). Cross-Border Payments Programme — https://www.bis.org/about/bisih/topics/fmis/cross-border.htm",
    ]},
  ],
  "supervised-features": [
    { type: "p", text: "If supervised access remains part of the product, it may include:" },
    { type: "ul", items: [
      "Parent or guardian oversight",
      "Under-18 access limitations defined by partner-bank policy",
      "Controlled spending and transfer rules",
      "Education content around fiat and crypto for younger users",
      "App controls and safety features such as limits, alerts, and approvals",
    ]},
  ],
  "supervised-restrictions": [
    { type: "ul", items: [
      "Jurisdictional restrictions on minor accounts",
      "Banking-partner requirements for KYC of a responsible adult",
    ]},
    { type: "callout", variant: "note", text: "Minors cannot open accounts without legal and partner-bank approval. All supervised-access features are subject to jurisdictional law, partner policy, and final product design." },
  ],
  "security-principles": [
    { type: "ul", items: [
      "Authentication — secure login, device binding, and step-up verification where required.",
      "Wallet protection — encrypted credentials, secure enclaves, and policy-based controls.",
      "Account recovery — clearly explained recovery paths consistent with the chosen wallet model.",
      "Device security — protections such as biometrics, screen-lock checks, and tamper detection.",
      "Transaction monitoring — automated review for unusual activity.",
      "Fraud monitoring — controls aligned with partner-bank and card-network rules.",
      "Partner security controls — leverage controls provided by banking, issuing, and infrastructure partners.",
      "Data protection — encryption in transit and at rest, access controls, and minimum-necessary data practices.",
      "User education — guidance to help users protect their wallets, accounts, and personal data.",
    ]},
  ],
  "user-responsibilities": [
    { type: "ul", items: [
      "Protect login credentials.",
      "Protect wallet recovery tools (seed phrase, passkeys, social recovery contacts, etc., depending on final model).",
      "Watch for phishing and impersonation.",
      "Verify transaction details before approving.",
      "Understand digital asset risks, including volatility and irreversibility of certain on-chain transactions.",
      "Follow compliance rules in your jurisdiction.",
    ]},
  ],
  "security-diagram": [
    { type: "flow", steps: [
      "User",
      "Login / Authentication",
      "Wallet Access",
      "Recovery Model / Transaction Activity",
      "Fraud / Risk Monitoring",
      "User Alerts / Review",
      "Data Privacy Controls",
    ]},
  ],
  "compliance-requirements": [
    { type: "p", text: "U-Topia operates within a regulated ecosystem. Requirements that may apply, depending on jurisdiction and partner program, include:" },
    { type: "ul", items: [
      "KYC (Know Your Customer)",
      "AML (Anti-Money Laundering)",
      "Sanctions screening",
      "Fraud controls",
      "Transaction monitoring",
      "Tax reporting considerations",
      "Data privacy (e.g., GDPR, CCPA, and equivalents)",
      "Jurisdictional restrictions",
      "Partner-bank rules",
      "Card-network rules",
    ]},
    { type: "callout", variant: "note", text: "[Confirm compliance provider] [Confirm data privacy policies] [Confirm legal entity and licensing structure]" },
  ],
  "compliance-flow": [
    { type: "flow", steps: [
      "User",
      "Identity Verification",
      "AML / Sanctions Screening",
      "Eligibility Review",
      "Partner Bank / Issuer Rules",
      "Approved Access (if eligible) / Restricted or Denied (if not)",
    ]},
  ],
  "risk-disclosures": [
    { type: "p", text: "Material risks users should understand:" },
    { type: "ul", items: [
      "Digital asset volatility — token and crypto prices can change significantly and rapidly.",
      "Wallet access loss — loss of credentials or recovery tools may result in loss of access.",
      "Regulatory changes — laws and supervisory positions can change and may affect features.",
      "Transaction delays — banking, network, or chain conditions can cause delays.",
      "Fees — fees may apply for various activities; final fee schedules are subject to partner and platform decisions.",
      "Account restrictions — partner-bank or issuer policies may restrict accounts.",
      "Partner availability — service depends on partners; partner changes may affect features.",
      "Jurisdictional restrictions — features may not be available in all regions.",
      "Security threats — phishing, malware, and social engineering risks.",
      "Data privacy risks — risks inherent to handling personal and financial data.",
      "Service interruptions — outages and maintenance windows may impact availability.",
    ]},
    { type: "callout", variant: "danger", title: "Crypto Risk Disclaimer", text: "Digital assets may be volatile and may not be protected by the same insurance or regulatory protections as traditional bank deposits. Users should understand the risks before using crypto-related features." },
  ],
  "infrastructure-map": [
    { type: "flow", steps: [
      "User → U-Topia App",
      "Web3 Non-Custodial Wallet",
      "KYC / Compliance Layer",
      "Banking Partner",
      "Issuing Partner / Program Manager",
      "Visa Network",
      "Crypto / Stablecoin Infrastructure",
      "Security and Risk Monitoring",
    ]},
  ],
  "partner-roles": [
    { type: "table", headers: ["Partner Type", "Role"], rows: [
      ["Banking partner", "Account access, compliance, settlement, regulated services"],
      ["Issuing partner", "Card/account credentials, transaction approval, network access"],
      ["Processor", "Transaction processing and authorization support"],
      ["Program manager", "Card program operations and rules"],
      ["Compliance provider", "KYC, AML, sanctions screening"],
      ["Blockchain provider", "Wallet infrastructure, network access"],
      ["Stablecoin provider", "Stablecoin infrastructure, if approved"],
      ["Data/security provider", "Fraud monitoring, authentication, device controls"],
    ]},
    { type: "callout", variant: "warning", text: "Confirm final partner list and roles before publishing any specific partner names." },
  ],
  "me-visa-crypto": [
    { type: "h3", text: "Topic" },
    { type: "p", text: "Visa's exploration of crypto and stablecoin settlement." },
    { type: "h3", text: "What external sources say" },
    { type: "p", text: "Visa has published material describing pilots and partnerships related to stablecoin settlement and crypto-linked card programs." },
    { type: "h3", text: "Why it matters for U-Topia" },
    { type: "p", text: "Demonstrates that the Visa network has been actively engaging with digital-asset settlement and card programs, which is the category U-Topia is designed to participate in via partners." },
    { type: "link", label: "corporate.visa.com — Visa Perspectives", href: "https://corporate.visa.com/en/sites/visa-perspectives.html" },
  ],
  "me-embedded-finance": [
    { type: "h3", text: "Topic" },
    { type: "p", text: "Embedded finance market growth." },
    { type: "h3", text: "What external sources say" },
    { type: "p", text: "Industry research from major consultancies indicates growing adoption of embedded financial services delivered through apps and non-bank brands." },
    { type: "h3", text: "Why it matters for U-Topia" },
    { type: "p", text: "U-Topia's partner-powered model fits within embedded-finance patterns where fintech apps deliver experiences and regulated partners provide the underlying services." },
    { type: "link", label: "McKinsey — Financial Services Insights", href: "https://www.mckinsey.com/industries/financial-services/our-insights" },
  ],
  "me-baas": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Banking-as-a-Service models." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Multiple reports describe the rise of BaaS, in which licensed banks offer regulated services to fintech partners via APIs." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "U-Topia depends on partner banks; BaaS is the operating pattern that makes its model possible." },
    { type: "link", label: "Bank for International Settlements", href: "https://www.bis.org/" },
  ],
  "me-bank-fintech": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Partnerships between banks and fintech apps." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Regulators in multiple jurisdictions have published guidance on responsible bank–fintech partnerships, including risk management expectations." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Highlights both the opportunity and the compliance expectations relevant to U-Topia's partner-led approach." },
    { type: "link", label: "Federal Reserve", href: "https://www.federalreserve.gov/" },
  ],
  "me-visa-developer": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Visa's developer platform and network connectivity." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Visa publishes documentation describing APIs and program-level access enabling fintech programs through partners." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Confirms that the technical and program pathways for Visa-linked credentials exist for partner-led programs." },
    { type: "link", label: "Visa Developer", href: "https://developer.visa.com/" },
  ],
  "me-tokenization": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Tokenization standards for digital wallets." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Card networks describe tokenization as a security mechanism that replaces card data with tokens for in-app and contactless use." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Tokenization is foundational to in-app and mobile wallet experiences that U-Topia is likely to integrate, subject to partner approval." },
    { type: "link", label: "Visa Token Service", href: "https://usa.visa.com/products/visa-token-service.html" },
  ],
  "me-non-custodial": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Non-custodial wallet design and user control." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Public documentation from the Ethereum Foundation and other Web3 sources describes non-custodial designs, account abstraction, and smart-wallet patterns." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Provides design references for U-Topia's wallet model." },
    { type: "link", label: "ethereum.org/en/wallets", href: "https://ethereum.org/en/wallets/" },
  ],
  "me-stablecoins": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Stablecoin usage in payments." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Reports from regulators, central banks, and research institutions describe growing usage of stablecoins in cross-border and payment scenarios." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Relevant if U-Topia supports stablecoins via approved infrastructure, subject to jurisdictional compliance." },
    { type: "link", label: "BIS Working Papers on Stablecoins", href: "https://www.bis.org/publ/work_stablecoin.htm" },
  ],
  "me-inclusion": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Financial inclusion data and trends." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "The World Bank's Global Findex Database documents access to accounts and digital financial services globally." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Provides context for U-Topia's global access ambition." },
    { type: "link", label: "World Bank Global Findex", href: "https://www.worldbank.org/en/publication/globalfindex" },
  ],
  "me-oversight": [
    { type: "h3", text: "Topic" }, { type: "p", text: "Supervisory expectations for fintech partnerships." },
    { type: "h3", text: "What external sources say" }, { type: "p", text: "Agencies including FinCEN, OCC, FDIC, and the Federal Reserve have published guidance on third-party risk management and bank–fintech partnerships." },
    { type: "h3", text: "Why it matters for U-Topia" }, { type: "p", text: "Confirms the importance of strong compliance, partner due diligence, and risk controls in U-Topia's model." },
    { type: "link", label: "FinCEN", href: "https://www.fincen.gov/" },
    { type: "link", label: "OCC", href: "https://www.occ.treas.gov/" },
    { type: "link", label: "FDIC", href: "https://www.fdic.gov/" },
  ],
  "roadmap-may-june": [
    { type: "p", text: "Getting the core product launch-ready. The first two months focus on hardening the app, validating real transactions, and getting every partner-facing piece into shape." },
    { type: "h3", text: "What this phase covers" },
    { type: "ul", items: [
      "Internal testing — daily product use and bug surfacing across the team",
      "Transaction validation — confirming on-chain and stablecoin flows behave correctly",
      "Wallet UX — refining the user experience for onboarding, sending, and receiving",
      "Stablecoin flows — making sure receive, hold, send, and spend work cleanly",
      "Compliance readiness — finalizing KYC/AML processes for launch jurisdictions",
      "Partner integration prep — preparing the technical handshake with banking and issuing partners",
      "Launch-region planning — selecting initial markets and confirming jurisdictional fit",
      "Support FAQs — building the first version of user-facing support content",
    ]},
  ],
  "roadmap-jul-aug": [
    { type: "p", text: "Real users, real feedback, real partners. July and August move U-Topia from internal testing to a controlled beta with real community members — leaders, ambassadors, and active U ecosystem members." },
    { type: "h3", text: "What this phase covers" },
    { type: "ul", items: [
      "Closed beta access — selected leaders, ambassadors, and active members test the live product",
      "Onboarding flow — testing the path from app download to first transaction",
      "Wallet recovery — validating the recovery model in real-user conditions",
      "Stablecoin send and receive — beta users move stablecoins through the app",
      "Card-account journeys — first tests of the Visa-linked account experience",
      "Feedback loops — structured input from beta cohorts back into the product",
      "Multilingual training — preparing materials for global rollout in multiple languages",
    ]},
  ],
  "roadmap-sept": [
    { type: "p", text: "Opening the door wider, getting launch-ready. September widens beta access, finalizes app-store readiness, and puts the product through serious stress before the October launch." },
    { type: "h3", text: "What this phase covers" },
    { type: "ul", items: [
      "Broader beta access — expanding from invited members to a wider pre-launch audience",
      "App-store readiness — submission, approvals, and final asset prep for iOS and Android",
      "UX refinements — last round of polish based on beta feedback",
      "Supported markets and limits — confirming which countries are live and what transaction limits apply",
      "Launch website — public-facing site, messaging, and conversion flows",
      "Product demos — recorded and live walkthroughs for press, partners, and community",
      "Compliance disclosures — finalizing terms, risk disclosures, and user-facing legal copy",
      "Stress testing — load and reliability testing ahead of public launch",
    ]},
  ],
  "roadmap-oct": [
    { type: "p", text: "Going live, in front of the world. October is the public moment. The product launches, the Flow Summit in Bangkok puts U-Topia on a global stage, and onboarding scales from beta cohorts to general availability." },
    { type: "h3", text: "What this phase covers" },
    { type: "ul", items: [
      "Official public launch — U-Topia goes live across supported markets",
      "Flow Summit in Bangkok — flagship event combining product reveal, demos, and community",
      "Product demos — live walkthroughs of wallet, stablecoin, and Visa-linked features",
      "Community activation — converting the 1,000+ ecosystem audience into active users",
      "New cohorts — onboarding the next wave of users beyond the initial community",
      "Global campaign — coordinated marketing across regions and languages",
      "Next-stage growth targets — setting the metrics and milestones for what comes after launch",
    ]},
    { type: "callout", variant: "note", text: "October goal: make U-Topia visible, usable, trusted, and ready for global momentum." },
  ],
  "roadmap-vision": [
    { type: "p", text: "A global financial access layer that helps users hold, move, and use money through one simple mobile app — combining a non-custodial Web3 wallet, stablecoins, fiat rails, and Visa-linked services through regulated partners." },
    { type: "p", text: "The flywheel: education → onboarding → app usage → financial utility → community growth." },
    { type: "h3", text: "Strategic Pillars" },
    { type: "ol", items: [
      "Product readiness — Stable wallet, onboarding, balances, history, notifications, recovery, and support.",
      "Stablecoin utility — Simple receive, hold, send, and spend paths where available and compliant.",
      "Visa-connected access — Account and card user journeys through approved banking and payment partners.",
      "Trust and compliance — KYC/AML, clear terms, user education, security, disclosures, and support.",
      "Community growth — Ongoing education, webinars, Academy programs, ambassadors, and regional language onboarding.",
    ]},
  ],
  "faqs": [
    { type: "h3", text: "1. What is U-Topia?" },
    { type: "p", text: "U-Topia is building an app that combines Web3 wallet ownership, fiat-and-crypto usability, and Visa-linked account access through banking and issuing partners." },
    { type: "h3", text: "2. Is U-Topia the same as U.CENTER?" },
    { type: "p", text: "No. U-Topia and U.CENTER are separate projects. U-Topia focuses on Web3 wallet and Visa-linked account access. U.CENTER focuses on community commerce, marketing DAO, referral distribution, ranks, and compensation systems." },
    { type: "h3", text: "3. Is U-Topia a bank?" },
    { type: "p", text: "No. U-Topia is not a bank. Banking, issuing, payment, settlement, and compliance services may be provided by regulated partners." },
    { type: "h3", text: "4. How does U-Topia connect to Visa?" },
    { type: "p", text: "Through regulated banking and issuing partners, where eligible users may receive account or payment credentials that connect to the Visa network." },
    { type: "h3", text: "5. Does U-Topia issue Visa cards directly?" },
    { type: "p", text: "No, U-Topia should not be described as directly issuing Visa cards unless legally approved. Issuance is handled by issuing partners." },
    { type: "h3", text: "6. What does non-custodial mean?" },
    { type: "p", text: "Non-custodial generally means the user controls access to the wallet rather than relying entirely on a centralized custodian. The precise control and recovery model depends on the final wallet architecture." },
    { type: "h3", text: "7. Who controls the wallet?" },
    { type: "p", text: "The user, subject to the chosen wallet model. In some designs, recovery may involve guardians, passkeys, or other mechanisms." },
    { type: "h3", text: "8. What happens if a user loses wallet access?" },
    { type: "p", text: "That depends on the final recovery model. In some non-custodial designs, loss of credentials may result in loss of access. U-Topia will publish clear guidance once the final model is confirmed." },
    { type: "h3", text: "9. Can anyone globally open an account?" },
    { type: "p", text: "No. Access is limited to eligible users in supported jurisdictions, subject to KYC, AML, sanctions screening, partner-bank requirements, and local law." },
    { type: "h3", text: "10. What does \"eligible user\" mean?" },
    { type: "p", text: "An eligible user is one who meets the platform's and partners' requirements for account access, including jurisdictional, identity, age, and risk-screening criteria." },
    { type: "h3", text: "11. What KYC is required?" },
    { type: "p", text: "KYC requirements depend on the partner program and jurisdiction. They typically include identity verification, document checks, and screening." },
    { type: "h3", text: "12. What countries are supported?" },
    { type: "p", text: "Supported countries depend on partner availability and regulation." },
    { type: "h3", text: "13. What currencies are supported?" },
    { type: "p", text: "[Confirm supported fiat currencies]" },
    { type: "h3", text: "14. What crypto assets are supported?" },
    { type: "p", text: "[Confirm supported crypto assets]" },
    { type: "h3", text: "15. Can users spend crypto with Visa?" },
    { type: "p", text: "This depends on the final product design, partner approvals, and jurisdictional rules. Spending crypto often involves conversion to fiat at the point of transaction." },
    { type: "h3", text: "16. Does U-Topia support stablecoins?" },
    { type: "p", text: "[Confirm stablecoin support]" },
    { type: "h3", text: "17. Are crypto balances insured?" },
    { type: "p", text: "Digital assets are not automatically insured. They may not be protected by the same insurance or regulatory protections as traditional bank deposits." },
    { type: "h3", text: "18. Does U-Topia guarantee account approval?" },
    { type: "p", text: "No. U-Topia does not guarantee account approval, card issuance, partner acceptance, transaction approval, asset value, or uninterrupted service." },
    { type: "h3", text: "19. Can users under 18 use U-Topia?" },
    { type: "p", text: "Only if supervised-access features are part of the final product, and only where legal and partner-bank approval allows." },
    { type: "h3", text: "20. What parental controls are available?" },
    { type: "p", text: "If supervised access is supported, controls may include spending limits, alerts, approvals, and oversight." },
    { type: "h3", text: "21. How does U-Topia protect users?" },
    { type: "p", text: "Through authentication, wallet protection, recovery design, transaction monitoring, fraud controls, partner-provided security, data protection, and user education." },
    { type: "h3", text: "22. What are the risks of using crypto?" },
    { type: "p", text: "Risks include volatility, irreversibility of certain transactions, security threats, regulatory changes, and reduced protections compared to bank deposits." },
    { type: "h3", text: "23. How are transactions processed?" },
    { type: "p", text: "Through approved infrastructure partners, including banking, issuing, processing, and network partners. Crypto transactions may involve wallet, blockchain, and stablecoin infrastructure where supported." },
    { type: "h3", text: "24. Who provides banking services?" },
    { type: "p", text: "Regulated banking partners. [Confirm final banking partners]" },
    { type: "h3", text: "25. Who provides issuing services?" },
    { type: "p", text: "Regulated issuing partners. [Confirm final issuing partners]" },
    { type: "h3", text: "26. How does U-Topia handle compliance?" },
    { type: "p", text: "Through KYC, AML, sanctions screening, partner-bank rules, jurisdictional checks, and risk controls." },
    { type: "h3", text: "27. How does U-Topia protect data?" },
    { type: "p", text: "Through encryption in transit and at rest, access controls, and privacy practices aligned with applicable law." },
    { type: "h3", text: "28. Are there fees?" },
    { type: "p", text: "[Confirm fees]" },
    { type: "h3", text: "29. Is U-Topia available on iOS and Android?" },
    { type: "p", text: "[Confirm iOS / Android availability and launch dates]" },
    { type: "h3", text: "30. How can partners work with U-Topia?" },
    { type: "p", text: "Banking partners, issuing partners, compliance providers, technology providers, and infrastructure partners may engage through dedicated partner pathways." },
  ],
  "glossary": [
    { type: "ul", items: [
      "U-Topia — A Web3 non-custodial wallet app designed to connect eligible users globally to Visa-linked financial accounts through regulated banking and issuing partners.",
      "Web3 — A category of technologies including blockchains, smart contracts, wallets, and tokens that emphasizes user-controlled digital identity and assets.",
      "Non-custodial wallet — A wallet design where the user, rather than a centralized custodian, controls access credentials.",
      "Private key — A secret cryptographic key that controls access to a wallet's funds and transactions.",
      "Wallet recovery — Mechanisms (seed phrases, social recovery, passkeys, MPC, etc.) used to restore access to a wallet.",
      "Smart wallet — A wallet implemented as a smart contract supporting programmable controls and permissions.",
      "Account abstraction — A wallet pattern where authorization logic is flexible, supporting features like session keys and policy-based controls.",
      "Visa network — The card and payment network operated by Visa that connects banks, issuers, processors, and merchants.",
      "Issuer — A regulated institution that issues cards or account credentials connected to a payment network.",
      "Banking partner — A regulated bank that provides accounts, compliance, and settlement services to a fintech app.",
      "Program manager — A party that manages card program operations and rules in coordination with banks and issuers.",
      "Processor — A party that processes card transactions and supports authorization, clearing, and settlement.",
      "Embedded finance — The delivery of financial services through non-bank apps or platforms via regulated partners.",
      "Banking-as-a-Service — A model where licensed banks deliver regulated services to fintech partners through APIs.",
      "KYC — Know Your Customer; identity verification requirements for financial services.",
      "AML — Anti-Money Laundering; controls intended to detect and prevent money laundering.",
      "Sanctions screening — Checks against sanctions lists to comply with applicable laws.",
      "Stablecoin — A digital asset designed to maintain a stable value, often pegged to a fiat currency.",
      "Fiat — Government-issued currency such as USD or EUR.",
      "Crypto — Digital assets that operate on blockchains.",
      "Virtual card — A card credential issued digitally for use without a physical card.",
      "Physical card — A traditional physical payment card.",
      "Tokenization — Replacing sensitive card or account data with a token to improve security in payments.",
      "Settlement — The process of transferring funds between parties to complete a transaction.",
      "Ledger — A record of accounts and balances; may be internal, partner-bank, or on-chain.",
      "Eligibility — Whether a user meets the criteria required to access a feature.",
      "Jurisdictional availability — Whether a feature is available in a given country or region.",
    ]},
  ],
  "references": [
    { type: "h3", text: "17.1 Visa Network and Crypto/Stablecoin Payments" },
    { type: "ul", items: [
      "Visa — Visa Perspectives — https://corporate.visa.com/en/sites/visa-perspectives.html",
      "Visa — Visa Token Service — https://usa.visa.com/products/visa-token-service.html",
      "Visa Developer — Visa Developer Platform — https://developer.visa.com/",
    ]},
    { type: "h3", text: "17.2 Embedded Finance and Banking-as-a-Service" },
    { type: "ul", items: [
      "McKinsey & Company — Financial Services Insights — https://www.mckinsey.com/industries/financial-services/our-insights",
      "Bank for International Settlements (BIS) — Working Papers and Speeches on Fintech — https://www.bis.org/",
    ]},
    { type: "h3", text: "17.3 Bank–Fintech Partnerships and Supervision" },
    { type: "ul", items: [
      "Federal Reserve — Supervisory Guidance on Third-Party Risk Management — https://www.federalreserve.gov/",
      "OCC — Risk Management Guidance — https://www.occ.treas.gov/",
      "FDIC — Risk Management Manual and Guidance — https://www.fdic.gov/",
      "FinCEN — Money Services Businesses and BSA Compliance — https://www.fincen.gov/",
    ]},
    { type: "h3", text: "17.4 Non-Custodial Wallets and Web3" },
    { type: "ul", items: [
      "Ethereum Foundation — Wallets — https://ethereum.org/en/wallets/",
      "Ethereum Foundation — Account Abstraction — https://ethereum.org/en/roadmap/account-abstraction/",
    ]},
    { type: "h3", text: "17.5 Stablecoins" },
    { type: "ul", items: [
      "BIS — Working Papers on Stablecoins — https://www.bis.org/publ/work_stablecoin.htm",
      "Financial Stability Board (FSB) — Global Stablecoin Recommendations — https://www.fsb.org/",
    ]},
    { type: "h3", text: "17.6 Global Financial Inclusion" },
    { type: "ul", items: [
      "World Bank — Global Findex Database — https://www.worldbank.org/en/publication/globalfindex",
      "World Bank — Remittance Prices Worldwide — https://remittanceprices.worldbank.org/",
    ]},
  ],
};
